[package]
name = "swim-app"
version = "0.1.0"
edition = "2018"
authors = ["Shendor <shendor1988@gmail.com>"]
description = "SWIM protocol demo"
readme = "README.md"
repository = "https://github.com/Shendor/swim-demo"
license = "MIT OR Apache-2.0"

[dependencies]
rand = "*"
mockall = "*"