name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always
  PUSH_PACKAGES: github.event_name == 'push'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      if: ${{ env.PUSH_PACKAGES }} == 'true'
      run: cargo test --verbose

    - name: Check toolchain
      if: success() && ${{ env.PUSH_PACKAGES }} == 'true'
      run: rustup show

#    - uses: katyo/publish-crates@v1
#      with:
#        registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
